### ISSUE TITLE
Miscellaneous files should run successfully

### ISSUE THREAD

**Issue by peterthenelson** [PandaStabber/Goldberg_et_al_2016#14]
- All of them can't be run successfully (often due to path reasons).
- I'd like to clean them up, but I can't really do that if I don't have them in a working state to begin with.
- I don't think I understand the purpose behind class_test (it doesn't get used anywhere; is it supposed to do what helper functions are currently doing?).
- I don't understand the logic in histogramVisualization. What is it doing that regular, built-in histogram things don't do?

**Comment by eli-s-goldberg** [comment]
The class test can be removed, although the purpose was to enable s generic class of parameters to be entered, and then converted, through a series of functions. This is done by functions that have lots of specific inputs (eg row.porosity). I envisioned making a generic class function that could be initialized by assigning row header names to entities:
def class pc(df = dataframe, porosity= 'porosity') ... Or whatever (hard to type on phone) 

The histogram visualization is not necessary here. It is from another file where I aggregate the results of the model runs within a cross validation loop to understand the model performance.
